<a href="https://colab.research.google.com/github/i-malur/bootcamp-data-analytics-mod5/blob/main/M%C3%B3dulo_05_%7C_DATA_WRANGLING.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Colab da aula: https://colab.research.google.com/drive/1rOrhbmdr5Vfiu3K8ME4e3mEL7pqcTJBE?usp=sharing

## Aulas 01 e 02

In [1]:
import pandas as pd
import numpy as np

In [2]:
url_research = 'https://raw.githubusercontent.com/i-malur/bootcamp-data-analytics-mod5/refs/heads/main/arquivos-csv/reasearch_people.csv'

In [3]:
df_research_people = pd.read_csv(url_research)

In [4]:
df_research_people.head()

,Unnamed: 0,Nome,Endereerço,Cidade,Estado,phone,anual_income,Estado Civil,AAge,n_filhos,Moradia,Food_restrictions,streaming,diariamente_sun blocker,Vai na Praia Mensalmente,Faz Academia,Compra e Lê Livros Todos os Anos,Quantidade de Livros Comprados,Autor Favorito,email
0,0,Maria Clara Novaes,NaN,Carvalho,Mato Grosso do Sul,(011) 3908 5991,86445.0,NaN,43.0,NaN,Quitada,Nenhuma,Globo Play,Sim,Não,Sim,NaN,NaN,NaN,mariaclaranovaes285@gemeil.com
1,1,Davi Lucca Pereira>,"Rodovia de Silveira, 67",NaN,Mato Grosso do Sul,NaN,31289.0,NaN,NaN,0.0,De favor,NaN,Todos,NaN,Não,Sim,Não,NaN,NaN,daviluccapereira933@exemplo.com
2,2,Sr. Caio Caldeira,"Residencial Freitas, 10",Carvalho,Rio Grande do Norte,NaN,NaN,S,60.0,NaN,Financiamento,Lactose e Glúten,NaN,Sim,Não,NaN,Sim,6.0,NaN,srcaiocaldeira626@gemeil.com
3,3,Kaique Azevedo%,NaN,Azevedo,Rio Grande do Sul,NaN,76264.0,Casado,26.0,4.0,Quitada,Lactose e Glúten,NaN,Não,Não,Não,Sim,0.0,Enzo Rezende,kaiqueazevedo731@rotmail.com
4,4,Pedro Moreira,"Colônia de Oliveira, 87",NaN,NaN,-0.'8--%/],53295.0,Casado,60.0,5.0,Financiamento,NaN,Globo Play,Sim,Sim,NaN,Sim,7.0,NaN,pedromoreira622@gemeil.com

In [5]:
df_research_people = df_research_people.drop(columns=['Unnamed: 0'])
df_research_people.head()

,Nome,Endereerço,Cidade,Estado,phone,anual_income,Estado Civil,AAge,n_filhos,Moradia,Food_restrictions,streaming,diariamente_sun blocker,Vai na Praia Mensalmente,Faz Academia,Compra e Lê Livros Todos os Anos,Quantidade de Livros Comprados,Autor Favorito,email
0,Maria Clara Novaes,NaN,Carvalho,Mato Grosso do Sul,(011) 3908 5991,86445.0,NaN,43.0,NaN,Quitada,Nenhuma,Globo Play,Sim,Não,Sim,NaN,NaN,NaN,mariaclaranovaes285@gemeil.com
1,Davi Lucca Pereira>,"Rodovia de Silveira, 67",NaN,Mato Grosso do Sul,NaN,31289.0,NaN,NaN,0.0,De favor,NaN,Todos,NaN,Não,Sim,Não,NaN,NaN,daviluccapereira933@exemplo.com
2,Sr. Caio Caldeira,"Residencial Freitas, 10",Carvalho,Rio Grande do Norte,NaN,NaN,S,60.0,NaN,Financiamento,Lactose e Glúten,NaN,Sim,Não,NaN,Sim,6.0,NaN,srcaiocaldeira626@gemeil.com
3,Kaique Azevedo%,NaN,Azevedo,Rio Grande do Sul,NaN,76264.0,Casado,26.0,4.0,Quitada,Lactose e Glúten,NaN,Não,Não,Não,Sim,0.0,Enzo Rezende,kaiqueazevedo731@rotmail.com
4,Pedro Moreira,"Colônia de Oliveira, 87",NaN,NaN,-0.'8--%/],53295.0,Casado,60.0,5.0,Financiamento,NaN,Globo Play,Sim,Sim,NaN,Sim,7.0,NaN,pedromoreira622@gemeil.com

In [6]:
df_research_people = df_research_people.rename(columns={
    'Endereerço':'Endereço',
    'phone':'Telefone',
    'anual_income':'Renda Atual',
    'AAge':'Idade',
    'n_filhos': 'Numero de Filhos',
    'Food_restrictions':'Restrições Alimentares',
    'streaming':'Streaming',
    'diariamente_sun blocker':'Usa Protetor Solar Diariamente',
    'email':'Email'
})

df_research_people.columns

Index(['Nome', 'Endereço', 'Cidade', 'Estado', 'Telefone', 'Renda Atual',
       'Estado Civil', 'Idade', 'Numero de Filhos', 'Moradia',
       'Restrições Alimentares', 'Streaming', 'Usa Protetor Solar Diariamente',
       'Vai na Praia Mensalmente', 'Faz Academia',
       'Compra e Lê Livros Todos os Anos', 'Quantidade de Livros Comprados',
       'Autor Favorito', 'Email'],
      dtype='object')

Segunda opção:

```python
novas_colunas = {
    'Endereerço':'Endereço',
    'phone':'Telefone',
    'anual_income':'Renda Atual',
    'AAge':'Idade',
    'n_filhos': 'Numero de Filhos',
    'Food_restrictions':'Restrições Alimentares',
    'streaming':'Streaming',
    'diariamente_sun blocker':'Usa Protetor Solar Diariamente',
    'email':'Email'
}

df_research_people = df_research_people.rename(columns=df_research_people, inplace=True)
```

inplace() -> serve para aplicar as alterações diretamente no DataFrame original, sem ter a necessidade de realizar uma cópia dele ou atribuí-lo novamente à variável

### Regex

Uma **Expressão Regular** (muito conhecida como **Regex** ou *Regular Expression*) é como se fosse um **super filtro de buscas** para textos.

Em vez buscar por uma palavra exata (como "cachorro"), usamos um padrão de códigos para encontrar tipos de caracteres (como "qualquer número", "qualquer letra maiúscula" ou "qualquer símbolo").

No código, o Pandas está usando o Regex para varrer o texto das colunas e fazer uma limpa.

#### O que significa o `\W` especificamente?

Na linguagem do Regex, os caracteres têm significados especiais. Existe uma diferença entre o **`\w`** (minúsculo) e o **`\W`** (maiúsculo):

* **`\w` (minúsculo):** Representa caracteres de "palavras" (letras, números e o sublinhado `_`).
* **`\W` (maiúsculo):** É o oposto direta do minúsculo. Ele representa **tudo o que NÃO é uma letra, número ou sublinhado**. Ou seja: espaços, pontos, vírgulas, arrobas (`@`), barras (`/`), traços (`-`), exclamações, etc.

Portanto, quando é rodado:

```python
df_research_people.str.replace('\W', '', regex=True)

```

> *" O Python procura por tudo que for símbolo, pontuação ou espaço (`\W`) e **substitua por nada** (`''`), ou seja, apague tudo e deixe só as letras e números juntos."*

#### Exemplos Práticos

| Texto Original | O que o `\W` encontra | Resultado após o `.replace()` |
| --- | --- | --- |
| `João_Silva` | NADA (o `_` faz parte do `\w`) | `João_Silva` |
| `João Silva` | O espaço em branco | `JoãoSilva` |
| `R$ 1.500,00` | `$`, o espaço, os pontos e a vírgula | `R150000` |
| `id-458/B` | O traço `-` e a barra `/` | `id458B` |

Nas versões mais recentes do Pandas, para usar o Regex dentro do `.str.replace()`, é necessário passar o argumento `regex=True` explicitamente, caso contrário o Pandas pode achar que estamos tentando buscar literalmente pelo texto `\W`.

O jeito mais seguro de escrever seria:

```python
df_research_people.str.replace(r'\W', '', regex=True) -> necessário o r antes de '\W'

```

### coluna Nome

In [7]:
# df_research_people['Nome'] = df_research_people['Nome'].str.replace(r'\W', '', regex=True)

In [8]:
# O ^ dentro do [^ ...] significa "NÃO".
# Remove números e símbolos, mantendo letras e espaços
df_research_people['Nome'] = df_research_people['Nome'].str.replace(r'[^a-zA-ZÀ-ÿ ]', '', regex=True)

In [9]:
df_research_people.head(5)

,Nome,Endereço,Cidade,Estado,Telefone,Renda Atual,Estado Civil,Idade,Numero de Filhos,Moradia,Restrições Alimentares,Streaming,Usa Protetor Solar Diariamente,Vai na Praia Mensalmente,Faz Academia,Compra e Lê Livros Todos os Anos,Quantidade de Livros Comprados,Autor Favorito,Email
0,Maria Clara Novaes,NaN,Carvalho,Mato Grosso do Sul,(011) 3908 5991,86445.0,NaN,43.0,NaN,Quitada,Nenhuma,Globo Play,Sim,Não,Sim,NaN,NaN,NaN,mariaclaranovaes285@gemeil.com
1,Davi Lucca Pereira,"Rodovia de Silveira, 67",NaN,Mato Grosso do Sul,NaN,31289.0,NaN,NaN,0.0,De favor,NaN,Todos,NaN,Não,Sim,Não,NaN,NaN,daviluccapereira933@exemplo.com
2,Sr Caio Caldeira,"Residencial Freitas, 10",Carvalho,Rio Grande do Norte,NaN,NaN,S,60.0,NaN,Financiamento,Lactose e Glúten,NaN,Sim,Não,NaN,Sim,6.0,NaN,srcaiocaldeira626@gemeil.com
3,Kaique Azevedo,NaN,Azevedo,Rio Grande do Sul,NaN,76264.0,Casado,26.0,4.0,Quitada,Lactose e Glúten,NaN,Não,Não,Não,Sim,0.0,Enzo Rezende,kaiqueazevedo731@rotmail.com
4,Pedro Moreira,"Colônia de Oliveira, 87",NaN,NaN,-0.'8--%/],53295.0,Casado,60.0,5.0,Financiamento,NaN,Globo Play,Sim,Sim,NaN,Sim,7.0,NaN,pedromoreira622@gemeil.com

### Coluna telefone

In [10]:
df_research_people['Telefone']

0         (011) 3908 5991
1                     NaN
2                     NaN
3                     NaN
4              -0.'8--%/]
5     +55 (084) 4591-2403
6            84 9687 5023
7              5}|#:}~<7~
8        +55 51 6868 3666
9                     NaN
10                    NaN
11          0900 093 9760
12                    NaN
13           81 2891-7504
14             ^{{52$,,78
15                    NaN
16           41 5504 8546
17           84 2319-1532
18          0800 612 6032
19                    NaN
20           51 5882 5998
21                    NaN
22             ;~).,-:5~=
23    +55 (021) 4719 9862
24        (084) 0305 6725
25        (011) 3410 5199
26                    NaN
27           84 6014-5325
28                    NaN
29       +55 71 7088-8329
30                    NaN
31           21 0712-6859
32       +55 51 2213 5603
33             8:<$9@\:~/
34       +55 51 8245 2336
35        (061) 5002 3548
36             '|2{938(=[
Name: Telefone, dtype: object

In [11]:
df_telefone = df_research_people['Telefone'].str.replace(r'[^0-9() +-]', '*', regex=True)

In [13]:
df_research_people.loc[df_telefone.str.contains('[*]', na=False), 'Telefone'] = np.nan #ignora NaN

In [14]:
df_research_people.head(10)

,Nome,Endereço,Cidade,Estado,Telefone,Renda Atual,Estado Civil,Idade,Numero de Filhos,Moradia,Restrições Alimentares,Streaming,Usa Protetor Solar Diariamente,Vai na Praia Mensalmente,Faz Academia,Compra e Lê Livros Todos os Anos,Quantidade de Livros Comprados,Autor Favorito,Email
0,Maria Clara Novaes,NaN,Carvalho,Mato Grosso do Sul,(011) 3908 5991,86445.0,NaN,43.0,NaN,Quitada,Nenhuma,Globo Play,Sim,Não,Sim,NaN,NaN,NaN,mariaclaranovaes285@gemeil.com
1,Davi Lucca Pereira,"Rodovia de Silveira, 67",NaN,Mato Grosso do Sul,NaN,31289.0,NaN,NaN,0.0,De favor,NaN,Todos,NaN,Não,Sim,Não,NaN,NaN,daviluccapereira933@exemplo.com
2,Sr Caio Caldeira,"Residencial Freitas, 10",Carvalho,Rio Grande do Norte,NaN,NaN,S,60.0,NaN,Financiamento,Lactose e Glúten,NaN,Sim,Não,NaN,Sim,6.0,NaN,srcaiocaldeira626@gemeil.com
3,Kaique Azevedo,NaN,Azevedo,Rio Grande do Sul,NaN,76264.0,Casado,26.0,4.0,Quitada,Lactose e Glúten,NaN,Não,Não,Não,Sim,0.0,Enzo Rezende,kaiqueazevedo731@rotmail.com
4,Pedro Moreira,"Colônia de Oliveira, 87",NaN,NaN,NaN,53295.0,Casado,60.0,5.0,Financiamento,NaN,Globo Play,Sim,Sim,NaN,Sim,7.0,NaN,pedromoreira622@gemeil.com
5,Sra Ana Júlia Castro,"Parque Olivia da Mata, 32",Nogueira dos Dourados,Rondônia,+55 (084) 4591-2403,54503.0,Solteiro,29.0,NaN,Aluguel,NaN,Netflix e HBO,NaN,Sim,Não,Sim,5.0,Marcelo Melo,sraanajliacastro740@gemeil.com
6,Erick Carvalho,"Sítio Farias, 264",NaN,Amazonas,84 9687 5023,NaN,D,26.0,NaN,Quitada,Lactose,NaN,Não,Sim,NaN,Não,NaN,NaN,erickcarvalho519@rotmail.com
7,Sra Ana Sophia Vieira,"Esplanada de Mendes, 72",NaN,NaN,NaN,93976.0,NaN,50.0,4.0,Aluguel,Nenhuma,NaN,Não,Não,NaN,Não,NaN,NaN,sraanasophiavieira974@gemeil.com
8,Davi Nascimento,"Rua da Paz, 72",Duarte,NaN,+55 51 6868 3666,65384.0,Divorciado,60.0,2.0,Aluguel,Nenhuma,Crunchyroll,Não,Sim,Sim,NaN,NaN,NaN,dav4inascimento856@rotmail.com
9,Juan da Mota,Viela das Neves,NaN,Espírito Santo,NaN,NaN,Divorciado,NaN,4.0,Aluguel,Lactose,Nenhum,NaN,Sim,NaN,Não,NaN,NaN,juandamota291@gemeil.com

### Estado civil

In [15]:
df_research_people['Estado Civil'] = df_research_people['Estado Civil'].replace(
    {
        'V':'Viuvo',
        'D':'Divorciado',
        'S':'Solteiro',
        'C':'Casado'
    }
)

In [16]:
df_research_people['Telefone']

0         (011) 3908 5991
1                     NaN
2                     NaN
3                     NaN
4                     NaN
5     +55 (084) 4591-2403
6            84 9687 5023
7                     NaN
8        +55 51 6868 3666
9                     NaN
10                    NaN
11          0900 093 9760
12                    NaN
13           81 2891-7504
14                    NaN
15                    NaN
16           41 5504 8546
17           84 2319-1532
18          0800 612 6032
19                    NaN
20           51 5882 5998
21                    NaN
22                    NaN
23    +55 (021) 4719 9862
24        (084) 0305 6725
25        (011) 3410 5199
26                    NaN
27           84 6014-5325
28                    NaN
29       +55 71 7088-8329
30                    NaN
31           21 0712-6859
32       +55 51 2213 5603
33                    NaN
34       +55 51 8245 2336
35        (061) 5002 3548
36                    NaN
Name: Telefone, dtype: object

A empresa CarriConstrutora contratou a empresa que você trabalha
para encontrar possíveis compradores para o seus novos empreendimentos.
A empresa quer entender as necessidades dos clientes, e quer informações
com:  
* Quais cliente devemos abordar;  
* Qual empreendimento nós devemos mostrá-los;  
* Esse cliente está em busca em investir em um imóvel ou comprar para
moradia?

Será feita a manipulação da fonte de dados dos clientes para responder as questões.

In [17]:
df_research_people.columns

Index(['Nome', 'Endereço', 'Cidade', 'Estado', 'Telefone', 'Renda Atual',
       'Estado Civil', 'Idade', 'Numero de Filhos', 'Moradia',
       'Restrições Alimentares', 'Streaming', 'Usa Protetor Solar Diariamente',
       'Vai na Praia Mensalmente', 'Faz Academia',
       'Compra e Lê Livros Todos os Anos', 'Quantidade de Livros Comprados',
       'Autor Favorito', 'Email'],
      dtype='object')

In [18]:
df_casa = df_research_people.copy()

In [19]:
df_casa.drop([
    'Estado Civil',
    'Streaming',
    'Restrições Alimentares',
    'Usa Protetor Solar Diariamente',
    'Compra e Lê Livros Todos os Anos',
    'Quantidade de Livros Comprados',
    'Autor Favorito'
], axis=1, inplace=True)

'''
O inplace=True é um parâmetro que diz ao pandas para modificar o DataFrame diretamente na memória, em vez de criar e devolver um DataFrame novo.
Ou seja, não é necessário atribuir na variável df_casa para realizar as modificações
'''

'\nO inplace=True é um parâmetro que diz ao pandas para modificar o DataFrame diretamente na memória, em vez de criar e devolver um DataFrame novo.\nOu seja, não é necessário atribuir na variável df_casa para realizar as modificações\n'

In [20]:
df_casa['Minha Casa Minha Vida'] = True
df_casa.head()

,Nome,Endereço,Cidade,Estado,Telefone,Renda Atual,Idade,Numero de Filhos,Moradia,Vai na Praia Mensalmente,Faz Academia,Email,Minha Casa Minha Vida
0,Maria Clara Novaes,NaN,Carvalho,Mato Grosso do Sul,(011) 3908 5991,86445.0,43.0,NaN,Quitada,Não,Sim,mariaclaranovaes285@gemeil.com,True
1,Davi Lucca Pereira,"Rodovia de Silveira, 67",NaN,Mato Grosso do Sul,NaN,31289.0,NaN,0.0,De favor,Não,Sim,daviluccapereira933@exemplo.com,True
2,Sr Caio Caldeira,"Residencial Freitas, 10",Carvalho,Rio Grande do Norte,NaN,NaN,60.0,NaN,Financiamento,Não,NaN,srcaiocaldeira626@gemeil.com,True
3,Kaique Azevedo,NaN,Azevedo,Rio Grande do Sul,NaN,76264.0,26.0,4.0,Quitada,Não,Não,kaiqueazevedo731@rotmail.com,True
4,Pedro Moreira,"Colônia de Oliveira, 87",NaN,NaN,NaN,53295.0,60.0,5.0,Financiamento,Sim,NaN,pedromoreira622@gemeil.com,True

In [21]:
df_casa['Investimento'] = np.where((df_casa.Moradia == 'Quitada') | (df_casa.Moradia == 'Financiamento'), True, False)

In [22]:
df_casa

,Nome,Endereço,Cidade,Estado,Telefone,Renda Atual,Idade,Numero de Filhos,Moradia,Vai na Praia Mensalmente,Faz Academia,Email,Minha Casa Minha Vida,Investimento
0,Maria Clara Novaes,NaN,Carvalho,Mato Grosso do Sul,(011) 3908 5991,86445.0,43.0,NaN,Quitada,Não,Sim,mariaclaranovaes285@gemeil.com,True,True
1,Davi Lucca Pereira,"Rodovia de Silveira, 67",NaN,Mato Grosso do Sul,NaN,31289.0,NaN,0.0,De favor,Não,Sim,daviluccapereira933@exemplo.com,True,False
2,Sr Caio Caldeira,"Residencial Freitas, 10",Carvalho,Rio Grande do Norte,NaN,NaN,60.0,NaN,Financiamento,Não,NaN,srcaiocaldeira626@gemeil.com,True,True
3,Kaique Azevedo,NaN,Azevedo,Rio Grande do Sul,NaN,76264.0,26.0,4.0,Quitada,Não,Não,kaiqueazevedo731@rotmail.com,True,True
4,Pedro Moreira,"Colônia de Oliveira, 87",NaN,NaN,NaN,53295.0,60.0,5.0,Financiamento,Sim,NaN,pedromoreira622@gemeil.com,True,True
5,Sra Ana Júlia Castro,"Parque Olivia da Mata, 32",Nogueira dos Dourados,Rondônia,+55 (084) 4591-2403,54503.0,29.0,NaN,Aluguel,Sim,Não,sraanajliacastro740@gemeil.com,True,False
6,Erick Carvalho,"Sítio Farias, 264",NaN,Amazonas,84 9687 5023,NaN,26.0,NaN,Quitada,Sim,NaN,erickcarvalho519@rotmail.com,True,True
7,Sra Ana Sophia Vieira,"Esplanada de Mendes, 72",NaN,NaN,NaN,93976.0,50.0,4.0,Aluguel,Não,NaN,sraanasophiavieira974@gemeil.com,True,False
8,Davi Nascimento,"Rua da Paz, 72",Duarte,NaN,+55 51 6868 3666,65384.0,60.0,2.0,Aluguel,Sim,Sim,dav4inascimento856@rotmail.com,True,False
9,Juan da Mota,Viela das Neves,NaN,Espírito Santo,NaN,NaN,NaN,4.0,Aluguel,Sim,NaN,juandamota291@gemeil.com,True,False
10,Stephany Pinto,"Residencial Breno Sales, 27",Fernandes do Oeste,NaN,NaN,NaN,65.0,5.0,NaN,NaN,Sim,stephanypinto486@rotmail.com,True,False
11,Joana Rezende,Recanto Oliveira,Caldeira,NaN,0900 093 9760,71627.0,63.0,2.0,Quitada,Sim,Não,joanarezende680@gemeil.com,True,True
12,Dra Letícia Ribeiro,"Quadra Campos, 40",Jesus Paulista,NaN,NaN,67068.0,22.0,NaN,NaN,NaN,Sim,draletciaribeiro370@rotmail.com,True,False
13,Beatriz Azevedo,NaN,Costela da Praia,Santa Catarina,81 2891-7504,86389.0,33.0,2.0,De favor,Sim,NaN,beatrizazevedo858@gemeil.com,True,False
14,André Monteiro,NaN,Vieira do Amparo,NaN,NaN,22826.0,NaN,NaN,Aluguel,Não,Sim,andrmonteiro689@gemeil.com,True,False
15,João Guilherme Porto,"Loteamento Lima, 619",Santos do Amparo,Mato Grosso do Sul,NaN,NaN,78.0,NaN,NaN,Sim,Sim,jooguilhermeporto349@exemplo.com,True,False
16,Augusto Rocha,"Ladeira Luana Pires, 177",Silveira de da Luz,NaN,41 5504 8546,95433.0,54.0,5.0,Quitada,NaN,Não,augustorocha201@gemeil.com,True,True
17,Srta Isabelly da Rocha,"Estação Olivia Dias, 777",Gonçalves do Oeste,NaN,84 2319-1532,NaN,NaN,1.0,Quitada,NaN,Não,srtaisabellydarocha503@gemeil.com,True,True
18,Heloísa Santos,"Praia Paulo da Rocha, 5",Aragão,Paraíba,0800 612 6032,45809.0,26.0,NaN,NaN,Não,Não,helosasantos598@rotmail.com,True,False
19,Calebe Azevedo,"Parque Alves, 220",NaN,Rio Grande do Norte,NaN,NaN,NaN,NaN,Quitada,Sim,NaN,calebeazevedo917@rotmail.com,True,True
20,Ana Alves,"Lago de Caldeira, 9",Caldeira,Paraíba,51 5882 5998,86973.0,18.0,NaN,NaN,Não,NaN,anaalves702@rotmail.com,True,False
21,Maria Fernanda Ribeiro,NaN,Gomes dos Dourados,Pará,NaN,48124.0,NaN,3.0,De favor,Sim,Não,mariafernandaribeiro421@exemplo.com,True,False
22,Samuel Jesus,"Condomínio Ribeiro, 55",NaN,Bahia,NaN,93085.0,52.0,NaN,Financiamento,Sim,Sim,samueljesus456@gemeil.com,True,True
23,Beatriz Ramos,NaN,Fernandes,Tocantins,+55 (021) 4719 9862,71448.0,34.0,2.0,De favor,Sim,NaN,beatrizramos384@gemeil.com,True,False
24,Dr Davi Cunha,"Via de Correia, 17",Barbosa,Tocantins,(084) 0305 6725,36994.0,40.0,NaN,NaN,NaN,Não,drdavicunha261@exemplo.com,True,False
25,Enrico Cavalcanti,Vale Barros,NaN,NaN,(011) 3410 5199,NaN,25.0,NaN,De favor,Sim,NaN,enricocavalcanti318@gemeil.com,True,False
26,Raquel Moura,"Passarela Luiza Araújo, 36",Pires de Teixeira,Pará,NaN,NaN,42.0,4.0,Quitada,NaN,Não,raquelmoura251@gemeil.com,True,True
27,Lorena Cardoso,NaN,Monteiro do Galho,Pernambuco,84 6014-5325,92410.0,39.0,0.0,Quitada,Sim,Sim,lorenacardoso729@rotmail.com,True,True
28,Diogo Caldeira,"Vila Kaique da Paz, 76",Novaes,NaN,NaN,NaN,36.0,4.0,NaN,Sim,NaN,diogocaldeira718@gemeil.com,True,False
29,Maria Gonçalves,"Vale Nogueira, 342",Moraes do Galho,NaN,+55 71 7088-8329,NaN,47.0,NaN,Financiamento,NaN,NaN,mariagonalves175@gemeil.com,True,True
30,Isadora Cardoso,"Sítio Fernandes, 47",Castro,Bahia,NaN,50056.0,30.0,1.0,NaN,Sim,Sim,isadoracardoso853@gemeil.com,True,False
31,Igor Ferreira,"Quadra de da Mata, 49",NaN,NaN,21 0712-6859,77504.0,NaN,2.0,Aluguel,Não,NaN,igorferreira546@exemplo.com,True,False
32,Sabrina Nunes,Quadra da Luz,Novaes da Mata,Pará,+55 51 2213 5603,56484.0,57.0,2.0,De favor,Sim,NaN,sabrinanunes864@exemplo.com,True,False
33,Pedro Miguel Silva,"Residencial de Rodrigues, 97",NaN,Distrito Federal,NaN,88600.0,67.0,5.0,Quitada,Não,NaN,pedromiguelsilva613@exemplo.com,True,True
34,Dra Clarice da Conceição,NaN,Cavalcanti do Campo,Amazonas,+55 51 8245 2336,NaN,31.0,NaN,NaN,Sim,NaN,draclaricedaconceio834@gemeil.com,True,False
35,Daniel Rodrigues,"Loteamento Mendes, 72",Sales de Rodrigues,Mato Grosso,(061) 5002 3548,76000.0,64.0,3.0,Quitada,NaN,Não,danielrodrigues211@gemeil.com,True,True
36,Isis Silva,"Vila da Mota, 6",da Luz da Prata,Rondônia,NaN,61280.0,62.0,4.0,Financiamento,Não,Não,isissilva623@exemplo.com,True,True

Uma empresa chamada Hillo, é uma empresa que está estudando o mercado e
quer encontrar uma parceria com uma empresa de Streeming(netflix, Disney
plus etc), mas gostaria de saber quais as empresas dariam o maior retorno
de investimento.
Eles podem fazer análise de machinelearningtambém com esses dados.

In [23]:
df_research_people.head()

,Nome,Endereço,Cidade,Estado,Telefone,Renda Atual,Estado Civil,Idade,Numero de Filhos,Moradia,Restrições Alimentares,Streaming,Usa Protetor Solar Diariamente,Vai na Praia Mensalmente,Faz Academia,Compra e Lê Livros Todos os Anos,Quantidade de Livros Comprados,Autor Favorito,Email
0,Maria Clara Novaes,NaN,Carvalho,Mato Grosso do Sul,(011) 3908 5991,86445.0,NaN,43.0,NaN,Quitada,Nenhuma,Globo Play,Sim,Não,Sim,NaN,NaN,NaN,mariaclaranovaes285@gemeil.com
1,Davi Lucca Pereira,"Rodovia de Silveira, 67",NaN,Mato Grosso do Sul,NaN,31289.0,NaN,NaN,0.0,De favor,NaN,Todos,NaN,Não,Sim,Não,NaN,NaN,daviluccapereira933@exemplo.com
2,Sr Caio Caldeira,"Residencial Freitas, 10",Carvalho,Rio Grande do Norte,NaN,NaN,Solteiro,60.0,NaN,Financiamento,Lactose e Glúten,NaN,Sim,Não,NaN,Sim,6.0,NaN,srcaiocaldeira626@gemeil.com
3,Kaique Azevedo,NaN,Azevedo,Rio Grande do Sul,NaN,76264.0,Casado,26.0,4.0,Quitada,Lactose e Glúten,NaN,Não,Não,Não,Sim,0.0,Enzo Rezende,kaiqueazevedo731@rotmail.com
4,Pedro Moreira,"Colônia de Oliveira, 87",NaN,NaN,NaN,53295.0,Casado,60.0,5.0,Financiamento,NaN,Globo Play,Sim,Sim,NaN,Sim,7.0,NaN,pedromoreira622@gemeil.com

In [24]:
df_streaming = df_research_people.copy()

In [25]:
df_streaming.drop([
    'Estado Civil',
    'Restrições Alimentares',
    'Usa Protetor Solar Diariamente',
    'Compra e Lê Livros Todos os Anos',
    'Quantidade de Livros Comprados',
    'Autor Favorito',
    'Faz Academia',
    'Moradia',
    'Vai na Praia Mensalmente'
], axis=1, inplace=True)

In [26]:
df_streaming.head()

,Nome,Endereço,Cidade,Estado,Telefone,Renda Atual,Idade,Numero de Filhos,Streaming,Email
0,Maria Clara Novaes,NaN,Carvalho,Mato Grosso do Sul,(011) 3908 5991,86445.0,43.0,NaN,Globo Play,mariaclaranovaes285@gemeil.com
1,Davi Lucca Pereira,"Rodovia de Silveira, 67",NaN,Mato Grosso do Sul,NaN,31289.0,NaN,0.0,Todos,daviluccapereira933@exemplo.com
2,Sr Caio Caldeira,"Residencial Freitas, 10",Carvalho,Rio Grande do Norte,NaN,NaN,60.0,NaN,NaN,srcaiocaldeira626@gemeil.com
3,Kaique Azevedo,NaN,Azevedo,Rio Grande do Sul,NaN,76264.0,26.0,4.0,NaN,kaiqueazevedo731@rotmail.com
4,Pedro Moreira,"Colônia de Oliveira, 87",NaN,NaN,NaN,53295.0,60.0,5.0,Globo Play,pedromoreira622@gemeil.com

In [27]:
df_streaming.Streaming = df_streaming.Streaming.replace({'Todos': 'Globo Play e Netflix e HBO e Crunchyroll e Disney Plus'})

In [28]:
df_streaming.Streaming = df_streaming.Streaming.replace({'Netflix e Disney': 'Netflix e Disney Plus'})

In [29]:
df_stream = df_streaming['Streaming'].str.get_dummies(sep=' e ')

In [30]:
df_streaming = pd.concat([df_streaming, df_stream], axis=1)

In [31]:
df_streaming.head()

,Nome,Endereço,Cidade,Estado,Telefone,Renda Atual,Idade,Numero de Filhos,Streaming,Email,Crunchyroll,Disney Plus,Globo Play,HBO,Nenhum,Netflix
0,Maria Clara Novaes,NaN,Carvalho,Mato Grosso do Sul,(011) 3908 5991,86445.0,43.0,NaN,Globo Play,mariaclaranovaes285@gemeil.com,0,0,1,0,0,0
1,Davi Lucca Pereira,"Rodovia de Silveira, 67",NaN,Mato Grosso do Sul,NaN,31289.0,NaN,0.0,Globo Play e Netflix e HBO e Crunchyroll e Dis...,daviluccapereira933@exemplo.com,1,1,1,1,0,1
2,Sr Caio Caldeira,"Residencial Freitas, 10",Carvalho,Rio Grande do Norte,NaN,NaN,60.0,NaN,NaN,srcaiocaldeira626@gemeil.com,0,0,0,0,0,0
3,Kaique Azevedo,NaN,Azevedo,Rio Grande do Sul,NaN,76264.0,26.0,4.0,NaN,kaiqueazevedo731@rotmail.com,0,0,0,0,0,0
4,Pedro Moreira,"Colônia de Oliveira, 87",NaN,NaN,NaN,53295.0,60.0,5.0,Globo Play,pedromoreira622@gemeil.com,0,0,1,0,0,0

Uma influenciadora digital de bem estar gostaria de analisar possíveis
empreendimentos dentro de diferentes propostas que recebe. Essas
propostas podem ser excludentes ou somatórias.

In [32]:
df_bem_estar = df_research_people.copy()

In [33]:
df_bem_estar.columns

Index(['Nome', 'Endereço', 'Cidade', 'Estado', 'Telefone', 'Renda Atual',
       'Estado Civil', 'Idade', 'Numero de Filhos', 'Moradia',
       'Restrições Alimentares', 'Streaming', 'Usa Protetor Solar Diariamente',
       'Vai na Praia Mensalmente', 'Faz Academia',
       'Compra e Lê Livros Todos os Anos', 'Quantidade de Livros Comprados',
       'Autor Favorito', 'Email'],
      dtype='object')

In [34]:
df_bem_estar.drop([
    'Estado Civil',
    'Streaming',
    'Moradia',
], axis=1, inplace=True)

In [35]:
restricao = df_bem_estar['Restrições Alimentares'].str.get_dummies(sep=' e ').drop(columns={'Nenhuma'})

In [42]:
restricao

    Glúten  Lactose
0        0        0
1        0        0
2        1        1
3        1        1
4        0        0
5        0        0
6        0        1
7        0        0
8        0        0
9        0        1
10       0        0
11       0        1
12       1        0
13       0        0
14       1        0
15       0        0
16       1        1
17       1        1
18       1        1
19       0        0
20       0        0
21       0        0
22       0        0
23       0        0
24       0        0
25       0        0
26       1        0
27       1        0
28       0        0
29       0        0
30       1        1
31       0        1
32       1        1
33       0        0
34       0        0
35       0        0
36       0        0

In [36]:
df_bem_estar = pd.concat([df_bem_estar, restricao], axis=1)

In [37]:
df_bem_estar.head()

,Nome,Endereço,Cidade,Estado,Telefone,Renda Atual,Idade,Numero de Filhos,Restrições Alimentares,Usa Protetor Solar Diariamente,Vai na Praia Mensalmente,Faz Academia,Compra e Lê Livros Todos os Anos,Quantidade de Livros Comprados,Autor Favorito,Email,Glúten,Lactose
0,Maria Clara Novaes,NaN,Carvalho,Mato Grosso do Sul,(011) 3908 5991,86445.0,43.0,NaN,Nenhuma,Sim,Não,Sim,NaN,NaN,NaN,mariaclaranovaes285@gemeil.com,0,0
1,Davi Lucca Pereira,"Rodovia de Silveira, 67",NaN,Mato Grosso do Sul,NaN,31289.0,NaN,0.0,NaN,NaN,Não,Sim,Não,NaN,NaN,daviluccapereira933@exemplo.com,0,0
2,Sr Caio Caldeira,"Residencial Freitas, 10",Carvalho,Rio Grande do Norte,NaN,NaN,60.0,NaN,Lactose e Glúten,Sim,Não,NaN,Sim,6.0,NaN,srcaiocaldeira626@gemeil.com,1,1
3,Kaique Azevedo,NaN,Azevedo,Rio Grande do Sul,NaN,76264.0,26.0,4.0,Lactose e Glúten,Não,Não,Não,Sim,0.0,Enzo Rezende,kaiqueazevedo731@rotmail.com,1,1
4,Pedro Moreira,"Colônia de Oliveira, 87",NaN,NaN,NaN,53295.0,60.0,5.0,NaN,Sim,Sim,NaN,Sim,7.0,NaN,pedromoreira622@gemeil.com,0,0

In [38]:
df_bem_estar['Idoso'] = np.where(df_bem_estar.Idade >= 60, True, False)

In [39]:
df_bem_estar

,Nome,Endereço,Cidade,Estado,Telefone,Renda Atual,Idade,Numero de Filhos,Restrições Alimentares,Usa Protetor Solar Diariamente,Vai na Praia Mensalmente,Faz Academia,Compra e Lê Livros Todos os Anos,Quantidade de Livros Comprados,Autor Favorito,Email,Glúten,Lactose,Idoso
0,Maria Clara Novaes,NaN,Carvalho,Mato Grosso do Sul,(011) 3908 5991,86445.0,43.0,NaN,Nenhuma,Sim,Não,Sim,NaN,NaN,NaN,mariaclaranovaes285@gemeil.com,0,0,False
1,Davi Lucca Pereira,"Rodovia de Silveira, 67",NaN,Mato Grosso do Sul,NaN,31289.0,NaN,0.0,NaN,NaN,Não,Sim,Não,NaN,NaN,daviluccapereira933@exemplo.com,0,0,False
2,Sr Caio Caldeira,"Residencial Freitas, 10",Carvalho,Rio Grande do Norte,NaN,NaN,60.0,NaN,Lactose e Glúten,Sim,Não,NaN,Sim,6.0,NaN,srcaiocaldeira626@gemeil.com,1,1,True
3,Kaique Azevedo,NaN,Azevedo,Rio Grande do Sul,NaN,76264.0,26.0,4.0,Lactose e Glúten,Não,Não,Não,Sim,0.0,Enzo Rezende,kaiqueazevedo731@rotmail.com,1,1,False
4,Pedro Moreira,"Colônia de Oliveira, 87",NaN,NaN,NaN,53295.0,60.0,5.0,NaN,Sim,Sim,NaN,Sim,7.0,NaN,pedromoreira622@gemeil.com,0,0,True
5,Sra Ana Júlia Castro,"Parque Olivia da Mata, 32",Nogueira dos Dourados,Rondônia,+55 (084) 4591-2403,54503.0,29.0,NaN,NaN,NaN,Sim,Não,Sim,5.0,Marcelo Melo,sraanajliacastro740@gemeil.com,0,0,False
6,Erick Carvalho,"Sítio Farias, 264",NaN,Amazonas,84 9687 5023,NaN,26.0,NaN,Lactose,Não,Sim,NaN,Não,NaN,NaN,erickcarvalho519@rotmail.com,0,1,False
7,Sra Ana Sophia Vieira,"Esplanada de Mendes, 72",NaN,NaN,NaN,93976.0,50.0,4.0,Nenhuma,Não,Não,NaN,Não,NaN,NaN,sraanasophiavieira974@gemeil.com,0,0,False
8,Davi Nascimento,"Rua da Paz, 72",Duarte,NaN,+55 51 6868 3666,65384.0,60.0,2.0,Nenhuma,Não,Sim,Sim,NaN,NaN,NaN,dav4inascimento856@rotmail.com,0,0,True
9,Juan da Mota,Viela das Neves,NaN,Espírito Santo,NaN,NaN,NaN,4.0,Lactose,NaN,Sim,NaN,Não,NaN,NaN,juandamota291@gemeil.com,0,1,False
10,Stephany Pinto,"Residencial Breno Sales, 27",Fernandes do Oeste,NaN,NaN,NaN,65.0,5.0,Nenhuma,Sim,NaN,Sim,Não,NaN,NaN,stephanypinto486@rotmail.com,0,0,True
11,Joana Rezende,Recanto Oliveira,Caldeira,NaN,0900 093 9760,71627.0,63.0,2.0,Lactose,Não,Sim,Não,Sim,5.0,NaN,joanarezende680@gemeil.com,0,1,True
12,Dra Letícia Ribeiro,"Quadra Campos, 40",Jesus Paulista,NaN,NaN,67068.0,22.0,NaN,Glúten,Não,NaN,Sim,Sim,NaN,Lorena Lopes,draletciaribeiro370@rotmail.com,1,0,False
13,Beatriz Azevedo,NaN,Costela da Praia,Santa Catarina,81 2891-7504,86389.0,33.0,2.0,NaN,Sim,Sim,NaN,Sim,NaN,Isis Santos,beatrizazevedo858@gemeil.com,0,0,False
14,André Monteiro,NaN,Vieira do Amparo,NaN,NaN,22826.0,NaN,NaN,Glúten,Não,Não,Sim,Sim,6.0,Nicolas Silveira,andrmonteiro689@gemeil.com,1,0,False
15,João Guilherme Porto,"Loteamento Lima, 619",Santos do Amparo,Mato Grosso do Sul,NaN,NaN,78.0,NaN,NaN,NaN,Sim,Sim,Sim,NaN,Sr. Lucas Ribeiro,jooguilhermeporto349@exemplo.com,0,0,True
16,Augusto Rocha,"Ladeira Luana Pires, 177",Silveira de da Luz,NaN,41 5504 8546,95433.0,54.0,5.0,Lactose e Glúten,Não,NaN,Não,Sim,3.0,Gabrielly da Mota,augustorocha201@gemeil.com,1,1,False
17,Srta Isabelly da Rocha,"Estação Olivia Dias, 777",Gonçalves do Oeste,NaN,84 2319-1532,NaN,NaN,1.0,Lactose e Glúten,Sim,NaN,Não,Sim,NaN,Amanda da Mota,srtaisabellydarocha503@gemeil.com,1,1,False
18,Heloísa Santos,"Praia Paulo da Rocha, 5",Aragão,Paraíba,0800 612 6032,45809.0,26.0,NaN,Lactose e Glúten,NaN,Não,Não,NaN,NaN,NaN,helosasantos598@rotmail.com,1,1,False
19,Calebe Azevedo,"Parque Alves, 220",NaN,Rio Grande do Norte,NaN,NaN,NaN,NaN,NaN,Não,Sim,NaN,NaN,NaN,NaN,calebeazevedo917@rotmail.com,0,0,False
20,Ana Alves,"Lago de Caldeira, 9",Caldeira,Paraíba,51 5882 5998,86973.0,18.0,NaN,NaN,Sim,Não,NaN,NaN,NaN,NaN,anaalves702@rotmail.com,0,0,False
21,Maria Fernanda Ribeiro,NaN,Gomes dos Dourados,Pará,NaN,48124.0,NaN,3.0,NaN,Não,Sim,Não,Sim,5.0,Manuela da Costa,mariafernandaribeiro421@exemplo.com,0,0,False
22,Samuel Jesus,"Condomínio Ribeiro, 55",NaN,Bahia,NaN,93085.0,52.0,NaN,Nenhuma,NaN,Sim,Sim,NaN,NaN,NaN,samueljesus456@gemeil.com,0,0,False
23,Beatriz Ramos,NaN,Fernandes,Tocantins,+55 (021) 4719 9862,71448.0,34.0,2.0,Nenhuma,Não,Sim,NaN,NaN,NaN,NaN,beatrizramos384@gemeil.com,0,0,False
24,Dr Davi Cunha,"Via de Correia, 17",Barbosa,Tocantins,(084) 0305 6725,36994.0,40.0,NaN,NaN,Sim,NaN,Não,NaN,NaN,NaN,drdavicunha261@exemplo.com,0,0,False
25,Enrico Cavalcanti,Vale Barros,NaN,NaN,(011) 3410 5199,NaN,25.0,NaN,NaN,NaN,Sim,NaN,NaN,NaN,NaN,enricocavalcanti318@gemeil.com,0,0,False
26,Raquel Moura,"Passarela Luiza Araújo, 36",Pires de Teixeira,Pará,NaN,NaN,42.0,4.0,Glúten,NaN,NaN,Não,Não,NaN,NaN,raquelmoura251@gemeil.com,1,0,False
27,Lorena Cardoso,NaN,Monteiro do Galho,Pernambuco,84 6014-5325,92410.0,39.0,0.0,Glúten,Sim,Sim,Sim,NaN,NaN,NaN,lorenacardoso729@rotmail.com,1,0,False
28,Diogo Caldeira,"Vila Kaique da Paz, 76",Novaes,NaN,NaN,NaN,36.0,4.0,Nenhuma,Sim,Sim,NaN,NaN,NaN,NaN,diogocaldeira718@gemeil.com,0,0,False
29,Maria Gonçalves,"Vale Nogueira, 342",Moraes do Galho,NaN,+55 71 7088-8329,NaN,47.0,NaN,Nenhuma,Sim,NaN,NaN,Sim,10.0,Sr. Luiz Fernando Vieira,mariagonalves175@gemeil.com,0,0,False
30,Isadora Cardoso,"Sítio Fernandes, 47",Castro,Bahia,NaN,50056.0,30.0,1.0,Lactose e Glúten,NaN,Sim,Sim,NaN,NaN,NaN,isadoracardoso853@gemeil.com,1,1,False
31,Igor Ferreira,"Quadra de da Mata, 49",NaN,NaN,21 0712-6859,77504.0,NaN,2.0,Lactose,NaN,Não,NaN,NaN,NaN,NaN,igorferreira546@exemplo.com,0,1,False
32,Sabrina Nunes,Quadra da Luz,Novaes da Mata,Pará,+55 51 2213 5603,56484.0,57.0,2.0,Lactose e Glúten,Sim,Sim,NaN,Sim,NaN,Ana Nascimento,sabrinanunes864@exemplo.com,1,1,False
33,Pedro Miguel Silva,"Residencial de Rodrigues, 97",NaN,Distrito Federal,NaN,88600.0,67.0,5.0,NaN,NaN,Não,NaN,NaN,NaN,NaN,pedromiguelsilva613@exemplo.com,0,0,True
34,Dra Clarice da Conceição,NaN,Cavalcanti do Campo,Amazonas,+55 51 8245 2336,NaN,31.0,NaN,NaN,Não,Sim,NaN,Sim,5.0,Emilly Peixoto,draclaricedaconceio834@gemeil.com,0,0,False
35,Daniel Rodrigues,"Loteamento Mendes, 72",Sales de Rodrigues,Mato Grosso,(061) 5002 3548,76000.0,64.0,3.0,Nenhuma,Não,NaN,Não,Não,NaN,NaN,danielrodrigues211@gemeil.com,0,0,True
36,Isis Silva,"Vila da Mota, 6",da Luz da Prata,Rondônia,NaN,61280.0,62.0,4.0,NaN,NaN,Não,Não,Não,NaN,NaN,isissilva623@exemplo.com,0,0,True

## ONE HOT CODE

##  O que é?

O One-Hot Encoding (ou codificação one-hot) é uma técnica usada para transformar variáveis categóricas (como textos, nomes ou categorias) em números, de um jeito que os modelos de machine learning consigam entender sem se confundirem.

No Pandas, usamos a função pd.get_dummies().

## Cenário de exemplo:

Imagine que temos uma coluna chamada "Animal" com três valores: Cachorro, Gato e Papagaio.

Se vamos substituir esses nomes por números (Cachorro = 1, Gato = 2, Papagaio = 3), o algoritmo de inteligência artificial pode achar que um Papagaio (3) é "maior" ou "melhor" que um Cachorro (1), ou que Cachorro + Gato = Papagaio.

O One-Hot Encoding resolve isso criando uma nova coluna para cada categoria. Ele preenche com 1 se a linha for daquela categoria e 0 se não for.

In [40]:
dados = pd.DataFrame({'Cor': ['Vermelho', 'Azul', 'Verde', 'Vermelho']})
print("Antes do One-Hot Encoding:")
print(dados)

Antes do One-Hot Encoding:
        Cor
0  Vermelho
1      Azul
2     Verde
3  Vermelho

In [41]:
dados = pd.get_dummies(dados, columns=['Cor'], dtype=int)
print("Depois do One-Hot Encoding:")
print(dados)

Depois do One-Hot Encoding:
   Cor_Azul  Cor_Verde  Cor_Vermelho
0         0          0             1
1         1          0             0
2         0          1             0
3         0          0             1