<a href="https://colab.research.google.com/github/i-malur/bootcamp-data-analytics-mod5/blob/main/M%C3%B3dulo_05_%7C_DATA_WRANGLING.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Colab da aula: https://colab.research.google.com/drive/1rOrhbmdr5Vfiu3K8ME4e3mEL7pqcTJBE?usp=sharing

## Aulas 01 e 02

In [1]:
import pandas as pd
import numpy as np

In [2]:
url_research = 'https://raw.githubusercontent.com/i-malur/bootcamp-data-analytics-mod5/refs/heads/main/arquivos-csv/reasearch_people.csv'

In [3]:
df_research_people = pd.read_csv(url_research)

In [4]:
df_research_people.head()

,Unnamed: 0,Nome,Endereerço,Cidade,Estado,phone,anual_income,Estado Civil,AAge,n_filhos,Moradia,Food_restrictions,streaming,diariamente_sun blocker,Vai na Praia Mensalmente,Faz Academia,Compra e Lê Livros Todos os Anos,Quantidade de Livros Comprados,Autor Favorito,email
0,0,Maria Clara Novaes,NaN,Carvalho,Mato Grosso do Sul,(011) 3908 5991,86445.0,NaN,43.0,NaN,Quitada,Nenhuma,Globo Play,Sim,Não,Sim,NaN,NaN,NaN,mariaclaranovaes285@gemeil.com
1,1,Davi Lucca Pereira>,"Rodovia de Silveira, 67",NaN,Mato Grosso do Sul,NaN,31289.0,NaN,NaN,0.0,De favor,NaN,Todos,NaN,Não,Sim,Não,NaN,NaN,daviluccapereira933@exemplo.com
2,2,Sr. Caio Caldeira,"Residencial Freitas, 10",Carvalho,Rio Grande do Norte,NaN,NaN,S,60.0,NaN,Financiamento,Lactose e Glúten,NaN,Sim,Não,NaN,Sim,6.0,NaN,srcaiocaldeira626@gemeil.com
3,3,Kaique Azevedo%,NaN,Azevedo,Rio Grande do Sul,NaN,76264.0,Casado,26.0,4.0,Quitada,Lactose e Glúten,NaN,Não,Não,Não,Sim,0.0,Enzo Rezende,kaiqueazevedo731@rotmail.com
4,4,Pedro Moreira,"Colônia de Oliveira, 87",NaN,NaN,-0.'8--%/],53295.0,Casado,60.0,5.0,Financiamento,NaN,Globo Play,Sim,Sim,NaN,Sim,7.0,NaN,pedromoreira622@gemeil.com

In [5]:
df_research_people = df_research_people.drop(columns=['Unnamed: 0'])
df_research_people.head()

,Nome,Endereerço,Cidade,Estado,phone,anual_income,Estado Civil,AAge,n_filhos,Moradia,Food_restrictions,streaming,diariamente_sun blocker,Vai na Praia Mensalmente,Faz Academia,Compra e Lê Livros Todos os Anos,Quantidade de Livros Comprados,Autor Favorito,email
0,Maria Clara Novaes,NaN,Carvalho,Mato Grosso do Sul,(011) 3908 5991,86445.0,NaN,43.0,NaN,Quitada,Nenhuma,Globo Play,Sim,Não,Sim,NaN,NaN,NaN,mariaclaranovaes285@gemeil.com
1,Davi Lucca Pereira>,"Rodovia de Silveira, 67",NaN,Mato Grosso do Sul,NaN,31289.0,NaN,NaN,0.0,De favor,NaN,Todos,NaN,Não,Sim,Não,NaN,NaN,daviluccapereira933@exemplo.com
2,Sr. Caio Caldeira,"Residencial Freitas, 10",Carvalho,Rio Grande do Norte,NaN,NaN,S,60.0,NaN,Financiamento,Lactose e Glúten,NaN,Sim,Não,NaN,Sim,6.0,NaN,srcaiocaldeira626@gemeil.com
3,Kaique Azevedo%,NaN,Azevedo,Rio Grande do Sul,NaN,76264.0,Casado,26.0,4.0,Quitada,Lactose e Glúten,NaN,Não,Não,Não,Sim,0.0,Enzo Rezende,kaiqueazevedo731@rotmail.com
4,Pedro Moreira,"Colônia de Oliveira, 87",NaN,NaN,-0.'8--%/],53295.0,Casado,60.0,5.0,Financiamento,NaN,Globo Play,Sim,Sim,NaN,Sim,7.0,NaN,pedromoreira622@gemeil.com

In [6]:
df_research_people = df_research_people.rename(columns={
    'Endereerço':'Endereço',
    'phone':'Telefone',
    'anual_income':'Renda Atual',
    'AAge':'Idade',
    'n_filhos': 'Numero de Filhos',
    'Food_restrictions':'Restrições Alimentares',
    'streaming':'Streaming',
    'diariamente_sun blocker':'Usa Protetor Solar Diariamente',
    'email':'Email'
})

df_research_people.columns

Index(['Nome', 'Endereço', 'Cidade', 'Estado', 'Telefone', 'Renda Atual',
       'Estado Civil', 'Idade', 'Numero de Filhos', 'Moradia',
       'Restrições Alimentares', 'Streaming', 'Usa Protetor Solar Diariamente',
       'Vai na Praia Mensalmente', 'Faz Academia',
       'Compra e Lê Livros Todos os Anos', 'Quantidade de Livros Comprados',
       'Autor Favorito', 'Email'],
      dtype='object')

Segunda opção:

```python
novas_colunas = {
    'Endereerço':'Endereço',
    'phone':'Telefone',
    'anual_income':'Renda Atual',
    'AAge':'Idade',
    'n_filhos': 'Numero de Filhos',
    'Food_restrictions':'Restrições Alimentares',
    'streaming':'Streaming',
    'diariamente_sun blocker':'Usa Protetor Solar Diariamente',
    'email':'Email'
}

df_research_people = df_research_people.rename(columns=df_research_people, inplace=True)
```

inplace() -> serve para aplicar as alterações diretamente no DataFrame original, sem ter a necessidade de realizar uma cópia dele ou atribuí-lo novamente à variável

### Regex

Uma **Expressão Regular** (muito conhecida como **Regex** ou *Regular Expression*) é como se fosse um **super filtro de buscas** para textos.

Em vez buscar por uma palavra exata (como "cachorro"), usamos um padrão de códigos para encontrar tipos de caracteres (como "qualquer número", "qualquer letra maiúscula" ou "qualquer símbolo").

No código, o Pandas está usando o Regex para varrer o texto das colunas e fazer uma limpa.

#### O que significa o `\W` especificamente?

Na linguagem do Regex, os caracteres têm significados especiais. Existe uma diferença entre o **`\w`** (minúsculo) e o **`\W`** (maiúsculo):

* **`\w` (minúsculo):** Representa caracteres de "palavras" (letras, números e o sublinhado `_`).
* **`\W` (maiúsculo):** É o oposto direta do minúsculo. Ele representa **tudo o que NÃO é uma letra, número ou sublinhado**. Ou seja: espaços, pontos, vírgulas, arrobas (`@`), barras (`/`), traços (`-`), exclamações, etc.

Portanto, quando é rodado:

```python
df_research_people.str.replace('\W', '', regex=True)

```

> *" O Python procura por tudo que for símbolo, pontuação ou espaço (`\W`) e **substitua por nada** (`''`), ou seja, apague tudo e deixe só as letras e números juntos."*

#### Exemplos Práticos

| Texto Original | O que o `\W` encontra | Resultado após o `.replace()` |
| --- | --- | --- |
| `João_Silva` | NADA (o `_` faz parte do `\w`) | `João_Silva` |
| `João Silva` | O espaço em branco | `JoãoSilva` |
| `R$ 1.500,00` | `$`, o espaço, os pontos e a vírgula | `R150000` |
| `id-458/B` | O traço `-` e a barra `/` | `id458B` |

Nas versões mais recentes do Pandas, para usar o Regex dentro do `.str.replace()`, é necessário passar o argumento `regex=True` explicitamente, caso contrário o Pandas pode achar que estamos tentando buscar literalmente pelo texto `\W`.

O jeito mais seguro de escrever seria:

```python
df_research_people.str.replace(r'\W', '', regex=True) -> necessário o r antes de '\W'

```

### coluna Nome

In [7]:
# df_research_people['Nome'] = df_research_people['Nome'].str.replace(r'\W', '', regex=True)

In [8]:
# O ^ dentro do [^ ...] significa "NÃO".
# Remove números e símbolos, mantendo letras e espaços
df_research_people['Nome'] = df_research_people['Nome'].str.replace(r'[^a-zA-ZÀ-ÿ ]', '', regex=True)

In [9]:
df_research_people.head(5)

,Nome,Endereço,Cidade,Estado,Telefone,Renda Atual,Estado Civil,Idade,Numero de Filhos,Moradia,Restrições Alimentares,Streaming,Usa Protetor Solar Diariamente,Vai na Praia Mensalmente,Faz Academia,Compra e Lê Livros Todos os Anos,Quantidade de Livros Comprados,Autor Favorito,Email
0,Maria Clara Novaes,NaN,Carvalho,Mato Grosso do Sul,(011) 3908 5991,86445.0,NaN,43.0,NaN,Quitada,Nenhuma,Globo Play,Sim,Não,Sim,NaN,NaN,NaN,mariaclaranovaes285@gemeil.com
1,Davi Lucca Pereira,"Rodovia de Silveira, 67",NaN,Mato Grosso do Sul,NaN,31289.0,NaN,NaN,0.0,De favor,NaN,Todos,NaN,Não,Sim,Não,NaN,NaN,daviluccapereira933@exemplo.com
2,Sr Caio Caldeira,"Residencial Freitas, 10",Carvalho,Rio Grande do Norte,NaN,NaN,S,60.0,NaN,Financiamento,Lactose e Glúten,NaN,Sim,Não,NaN,Sim,6.0,NaN,srcaiocaldeira626@gemeil.com
3,Kaique Azevedo,NaN,Azevedo,Rio Grande do Sul,NaN,76264.0,Casado,26.0,4.0,Quitada,Lactose e Glúten,NaN,Não,Não,Não,Sim,0.0,Enzo Rezende,kaiqueazevedo731@rotmail.com
4,Pedro Moreira,"Colônia de Oliveira, 87",NaN,NaN,-0.'8--%/],53295.0,Casado,60.0,5.0,Financiamento,NaN,Globo Play,Sim,Sim,NaN,Sim,7.0,NaN,pedromoreira622@gemeil.com

### Coluna telefone

In [10]:
df_research_people['Telefone']

0         (011) 3908 5991
1                     NaN
2                     NaN
3                     NaN
4              -0.'8--%/]
5     +55 (084) 4591-2403
6            84 9687 5023
7              5}|#:}~<7~
8        +55 51 6868 3666
9                     NaN
10                    NaN
11          0900 093 9760
12                    NaN
13           81 2891-7504
14             ^{{52$,,78
15                    NaN
16           41 5504 8546
17           84 2319-1532
18          0800 612 6032
19                    NaN
20           51 5882 5998
21                    NaN
22             ;~).,-:5~=
23    +55 (021) 4719 9862
24        (084) 0305 6725
25        (011) 3410 5199
26                    NaN
27           84 6014-5325
28                    NaN
29       +55 71 7088-8329
30                    NaN
31           21 0712-6859
32       +55 51 2213 5603
33             8:<$9@\:~/
34       +55 51 8245 2336
35        (061) 5002 3548
36             '|2{938(=[
Name: Telefone, dtype: object

In [11]:
df_telefone = df_research_people['Telefone'].str.replace(r'[^0-9() +-]', '*', regex=True)

In [13]:
df_research_people.loc[df_telefone.str.contains('[*]', na=False), 'Telefone'] = np.nan

In [26]:
df_research_people.head(10)

,Nome,Endereço,Cidade,Estado,Telefone,Renda Atual,Estado Civil,Idade,Numero de Filhos,Moradia,Restrições Alimentares,Streaming,Usa Protetor Solar Diariamente,Vai na Praia Mensalmente,Faz Academia,Compra e Lê Livros Todos os Anos,Quantidade de Livros Comprados,Autor Favorito,Email
0,Maria Clara Novaes,NaN,Carvalho,Mato Grosso do Sul,(011) 3908 5991,86445.0,NaN,43.0,NaN,Quitada,Nenhuma,Globo Play,Sim,Não,Sim,NaN,NaN,NaN,mariaclaranovaes285@gemeil.com
1,Davi Lucca Pereira,"Rodovia de Silveira, 67",NaN,Mato Grosso do Sul,NaN,31289.0,NaN,NaN,0.0,De favor,NaN,Todos,NaN,Não,Sim,Não,NaN,NaN,daviluccapereira933@exemplo.com
2,Sr Caio Caldeira,"Residencial Freitas, 10",Carvalho,Rio Grande do Norte,NaN,NaN,Solteiro,60.0,NaN,Financiamento,Lactose e Glúten,NaN,Sim,Não,NaN,Sim,6.0,NaN,srcaiocaldeira626@gemeil.com
3,Kaique Azevedo,NaN,Azevedo,Rio Grande do Sul,NaN,76264.0,Casado,26.0,4.0,Quitada,Lactose e Glúten,NaN,Não,Não,Não,Sim,0.0,Enzo Rezende,kaiqueazevedo731@rotmail.com
4,Pedro Moreira,"Colônia de Oliveira, 87",NaN,NaN,NaN,53295.0,Casado,60.0,5.0,Financiamento,NaN,Globo Play,Sim,Sim,NaN,Sim,7.0,NaN,pedromoreira622@gemeil.com
5,Sra Ana Júlia Castro,"Parque Olivia da Mata, 32",Nogueira dos Dourados,Rondônia,+55 (084) 4591-2403,54503.0,Solteiro,29.0,NaN,Aluguel,NaN,Netflix e HBO,NaN,Sim,Não,Sim,5.0,Marcelo Melo,sraanajliacastro740@gemeil.com
6,Erick Carvalho,"Sítio Farias, 264",NaN,Amazonas,84 9687 5023,NaN,Divorciado,26.0,NaN,Quitada,Lactose,NaN,Não,Sim,NaN,Não,NaN,NaN,erickcarvalho519@rotmail.com
7,Sra Ana Sophia Vieira,"Esplanada de Mendes, 72",NaN,NaN,NaN,93976.0,NaN,50.0,4.0,Aluguel,Nenhuma,NaN,Não,Não,NaN,Não,NaN,NaN,sraanasophiavieira974@gemeil.com
8,Davi Nascimento,"Rua da Paz, 72",Duarte,NaN,+55 51 6868 3666,65384.0,Divorciado,60.0,2.0,Aluguel,Nenhuma,Crunchyroll,Não,Sim,Sim,NaN,NaN,NaN,dav4inascimento856@rotmail.com
9,Juan da Mota,Viela das Neves,NaN,Espírito Santo,NaN,NaN,Divorciado,NaN,4.0,Aluguel,Lactose,Nenhum,NaN,Sim,NaN,Não,NaN,NaN,juandamota291@gemeil.com

### Estado civil

In [21]:
df_research_people['Estado Civil'] = df_research_people['Estado Civil'].replace(
    {
        'V':'Viuvo',
        'D':'Divorciado',
        'S':'Solteiro',
        'C':'Casado'
    }
)

In [24]:
df_research_people['Telefone']

0         (011) 3908 5991
1                     NaN
2                     NaN
3                     NaN
4                     NaN
5     +55 (084) 4591-2403
6            84 9687 5023
7                     NaN
8        +55 51 6868 3666
9                     NaN
10                    NaN
11          0900 093 9760
12                    NaN
13           81 2891-7504
14                    NaN
15                    NaN
16           41 5504 8546
17           84 2319-1532
18          0800 612 6032
19                    NaN
20           51 5882 5998
21                    NaN
22                    NaN
23    +55 (021) 4719 9862
24        (084) 0305 6725
25        (011) 3410 5199
26                    NaN
27           84 6014-5325
28                    NaN
29       +55 71 7088-8329
30                    NaN
31           21 0712-6859
32       +55 51 2213 5603
33                    NaN
34       +55 51 8245 2336
35        (061) 5002 3548
36                    NaN
Name: Telefone, dtype: object